-- Drop child tables first (those referencing others)
DROP TABLE IF EXISTS ORDER_ITEMS;
DROP TABLE IF EXISTS INVENTORY_RECEIVING;

-- Drop tables that reference parent tables
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS ALBUMS;
DROP TABLE IF EXISTS MOVIES;
DROP TABLE IF EXISTS PRODUCTS;

-- Drop parent/reference tables last
DROP TABLE IF EXISTS ARTISTS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS RATINGS;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS EMPLOYEE;